// Copyright 2026 datpaq. Licensed under Apache-2.0. See LICENSE.
// Hand-authored: browser-based Clerk SSO login flow. Not generated by
// printing-press — survives `--force` regenerations via AST-based merge.
//
// Wire contract is documented in docs/cli-auth-spec.md (repo-relative).

package cli

import (
	"bytes"
	"context"
	"crypto/rand"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net"
	"net/http"
	"net/url"
	"time"

	"github.com/datpaq/cli/internal/cliutil"
	"github.com/datpaq/cli/internal/config"
	"github.com/spf13/cobra"
)

// Defaults are package-level so tests / verify mode can override without
// reaching into the cobra command builder.
var (
	authLoginAuthURL      = "https://datpaq.com/cli/auth"
	authLoginExchangeURL  = "https://datpaq.com/api/internal/cli/auth/exchange"
	authLoginDefaultWait  = 5 * time.Minute
	authLoginCallbackPath = "/callback"
)

// exchangeResponse mirrors the body documented in cli-auth-spec.md §"Endpoint 2".
type exchangeResponse struct {
	APIKey    string `json:"api_key"`
	ExpiresAt string `json:"expires_at,omitempty"`
	User      struct {
		ID    string `json:"id"`
		Email string `json:"email"`
	} `json:"user"`
}

func newAuthLoginCmd(flags *rootFlags) *cobra.Command {
	var (
		noBrowser   bool
		timeout     time.Duration
		authURL     string
		exchangeURL string
	)
	cmd := &cobra.Command{
		Use:   "login",
		Short: "Sign in via the datpaq.com browser flow (Clerk SSO)",
		Long: "Opens your browser to datpaq.com for Clerk-backed sign-in " +
			"(Google, GitHub, or email/password), then captures your API key " +
			"via a one-shot loopback listener and saves it to the local config.\n\n" +
			"Use `datpaq auth set-token <key>` instead when you can't reach a " +
			"browser (SSH, CI, headless).",
		Example: "  datpaq auth login\n  datpaq auth login --no-browser",
		RunE: func(cmd *cobra.Command, args []string) error {
			// Short-circuit in the printing-press verify sandbox so dogfood
			// runs don't try to open browsers or bind sockets.
			if cliutil.IsVerifyEnv() {
				fmt.Fprintln(cmd.OutOrStdout(), "would open browser-based login flow")
				return nil
			}

			cfg, err := config.Load(flags.configPath)
			if err != nil {
				return configErr(err)
			}

			// Resolve effective URLs: flag overrides win, otherwise use the
			// production defaults. The flags are primarily for local dev
			// against a localhost website / staging environments.
			effectiveAuthURL := authURL
			if effectiveAuthURL == "" {
				effectiveAuthURL = authLoginAuthURL
			}
			effectiveExchangeURL := exchangeURL
			if effectiveExchangeURL == "" {
				effectiveExchangeURL = authLoginExchangeURL
			}

			state, err := randomNonce(32)
			if err != nil {
				return fmt.Errorf("generating state nonce: %w", err)
			}

			// Bind a loopback listener on an ephemeral port. ":0" lets the
			// kernel pick — avoids fighting other CLIs over a fixed port.
			ln, err := net.Listen("tcp", "127.0.0.1:0")
			if err != nil {
				return fmt.Errorf("binding loopback listener: %w", err)
			}
			port := ln.Addr().(*net.TCPAddr).Port

			// Buffered so the handler can send-and-return even if RunE has
			// already moved on (e.g. timeout fired first).
			resultCh := make(chan callbackResult, 1)
			srv := &http.Server{
				Handler:           buildCallbackMux(state, resultCh),
				ReadHeaderTimeout: 5 * time.Second,
			}
			go func() { _ = srv.Serve(ln) }()
			defer func() {
				shutdownCtx, cancel := context.WithTimeout(context.Background(), 2*time.Second)
				defer cancel()
				_ = srv.Shutdown(shutdownCtx)
			}()

			browserURL := buildAuthURL(effectiveAuthURL, port, state)
			w := cmd.OutOrStdout()
			fmt.Fprintln(w, "Opening browser to sign in…")
			fmt.Fprintln(w, "  ", browserURL)
			fmt.Fprintln(w, "")
			fmt.Fprintln(w, "Waiting for callback. Press Ctrl+C to cancel.")

			if !noBrowser {
				if err := openSetupURL(browserURL); err != nil {
					fmt.Fprintf(cmd.ErrOrStderr(),
						"could not open browser automatically (%v); open the URL above manually.\n", err)
				}
			}

			deadline := time.NewTimer(timeout)
			defer deadline.Stop()

			select {
			case <-deadline.C:
				return fmt.Errorf("timed out after %s waiting for browser callback", timeout)
			case res := <-resultCh:
				if res.err != nil {
					return res.err
				}
				exch, err := exchangeCode(cmd.Context(), effectiveExchangeURL, res.code, state)
				if err != nil {
					return fmt.Errorf("exchanging code for API key: %w", err)
				}
				if exch.APIKey == "" {
					return fmt.Errorf("exchange response missing api_key")
				}
				// Clear any stale auth_header so SaveCredential's slot is the
				// one AuthHeader() reads. Mirrors the pattern in set-token.
				cfg.AuthHeaderVal = ""
				if err := cfg.SaveCredential(exch.APIKey); err != nil {
					return configErr(fmt.Errorf("saving API key: %w", err))
				}

				if flags.asJSON {
					return printJSONFiltered(w, map[string]any{
						"logged_in":   true,
						"user_email":  exch.User.Email,
						"user_id":     exch.User.ID,
						"config_path": cfg.Path,
					}, flags)
				}
				fmt.Fprintf(w, "\n✓ Logged in as %s\n", exch.User.Email)
				fmt.Fprintf(w, "  API key saved to %s\n", cfg.Path)
				return nil
			}
		},
	}
	cmd.Flags().BoolVar(&noBrowser, "no-browser", false,
		"Print the auth URL but do not auto-open the browser")
	cmd.Flags().DurationVar(&timeout, "timeout", authLoginDefaultWait,
		"How long to wait for the browser callback")
	cmd.Flags().StringVar(&authURL, "auth-url", "",
		"Override the browser sign-in URL (advanced; for local dev against a non-production website)")
	cmd.Flags().StringVar(&exchangeURL, "exchange-url", "",
		"Override the code-exchange endpoint URL (advanced; for local dev against a non-production website)")
	return cmd
}

// callbackResult is what the loopback handler sends back to the command
// goroutine. Either code is set (success) or err is set (validation failure).
type callbackResult struct {
	code string
	err  error
}

func buildCallbackMux(expectedState string, ch chan<- callbackResult) http.Handler {
	mux := http.NewServeMux()
	mux.HandleFunc(authLoginCallbackPath, func(w http.ResponseWriter, r *http.Request) {
		q := r.URL.Query()
		gotState := q.Get("state")
		code := q.Get("code")

		// CSRF defense: the state we generated must come back verbatim.
		// Without this check, a malicious page on any origin could forge a
		// callback while the listener is up and inject an attacker-controlled
		// code.
		if gotState != expectedState {
			http.Error(w, "state mismatch", http.StatusBadRequest)
			select {
			case ch <- callbackResult{err: fmt.Errorf("callback state mismatch (possible CSRF)")}:
			default:
			}
			return
		}
		if code == "" {
			msg := q.Get("error_description")
			if msg == "" {
				msg = q.Get("error")
			}
			if msg == "" {
				msg = "callback missing 'code' query parameter"
			}
			http.Error(w, msg, http.StatusBadRequest)
			select {
			case ch <- callbackResult{err: fmt.Errorf("login failed: %s", msg)}:
			default:
			}
			return
		}

		w.Header().Set("Content-Type", "text/html; charset=utf-8")
		_, _ = w.Write([]byte(callbackSuccessHTML))
		select {
		case ch <- callbackResult{code: code}:
		default:
		}
	})
	return mux
}

func buildAuthURL(baseURL string, port int, state string) string {
	u, err := url.Parse(baseURL)
	if err != nil {
		// Parse failures are only reachable via a malformed --auth-url
		// override; fall back to a string-concatenated URL so the user at
		// least sees what the CLI tried.
		return fmt.Sprintf("%s?port=%d&state=%s", baseURL, port, state)
	}
	q := u.Query()
	q.Set("port", fmt.Sprintf("%d", port))
	q.Set("state", state)
	u.RawQuery = q.Encode()
	return u.String()
}

func exchangeCode(ctx context.Context, exchangeURL, code, state string) (*exchangeResponse, error) {
	body, err := json.Marshal(map[string]string{"code": code, "state": state})
	if err != nil {
		return nil, err
	}
	reqCtx, cancel := context.WithTimeout(ctx, 30*time.Second)
	defer cancel()
	req, err := http.NewRequestWithContext(reqCtx, http.MethodPost, exchangeURL, bytes.NewReader(body))
	if err != nil {
		return nil, err
	}
	req.Header.Set("Content-Type", "application/json")
	req.Header.Set("Accept", "application/json")

	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		var errBody struct {
			Error   string `json:"error"`
			Message string `json:"message"`
		}
		_ = json.NewDecoder(resp.Body).Decode(&errBody)
		switch {
		case errBody.Message != "":
			return nil, fmt.Errorf("HTTP %d: %s", resp.StatusCode, errBody.Message)
		case errBody.Error != "":
			return nil, fmt.Errorf("HTTP %d: %s", resp.StatusCode, errBody.Error)
		default:
			return nil, fmt.Errorf("HTTP %d from exchange endpoint", resp.StatusCode)
		}
	}

	var out exchangeResponse
	if err := json.NewDecoder(resp.Body).Decode(&out); err != nil {
		return nil, fmt.Errorf("decoding exchange response: %w", err)
	}
	return &out, nil
}

func randomNonce(n int) (string, error) {
	b := make([]byte, n)
	if _, err := rand.Read(b); err != nil {
		return "", err
	}
	return base64.RawURLEncoding.EncodeToString(b), nil
}

const callbackSuccessHTML = `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Datpaq CLI | Signed in</title>
<style>
  :root {
    --background: #ffffff;
    --foreground: #0a0a0a;
    --muted-foreground: #737373;
    --success: #37ce7b;
    --success-foreground: #12683b;
    --success-background: #ebfaf2;
    --font-body: Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
    --font-heading: "DM Sans", Inter, ui-sans-serif, system-ui, sans-serif;
  }

  * { box-sizing: border-box; }

  html { min-height: 100%; }

  body {
    margin: 0;
    min-height: 100%;
    background: var(--background);
    color: var(--foreground);
    font-family: var(--font-body);
    -webkit-font-smoothing: antialiased;
    text-rendering: optimizeLegibility;
  }

  a { color: inherit; }

  .page {
    display: flex;
    min-height: 100dvh;
    flex-direction: column;
  }

  .site-header {
    display: flex;
    min-height: 76px;
    align-items: center;
    justify-content: flex-start;
    padding: 0 clamp(1.25rem, 4vw, 4rem);
  }

  .wordmark {
    color: var(--foreground);
    font-family: var(--font-heading);
    font-size: 2rem;
    font-weight: 900;
    letter-spacing: -0.08em;
    line-height: 1;
    text-decoration: none;
  }

  main {
    display: grid;
    flex: 1;
    place-items: center;
    padding: clamp(4rem, 9vw, 8rem) 1.5rem;
  }

  .success {
    max-width: 42rem;
    text-align: center;
  }

  .success-icon {
    display: inline-grid;
    width: clamp(5.5rem, 10vw, 6.5rem);
    height: clamp(5.5rem, 10vw, 6.5rem);
    place-items: center;
    border: 2px solid var(--success);
    border-radius: 999px;
    background: var(--success-background);
    color: var(--success-foreground);
    font-size: clamp(2.75rem, 6vw, 3.5rem);
    font-weight: 800;
    line-height: 1;
  }

  h1 {
    margin: 2rem 0 0;
    font-family: var(--font-heading);
    font-size: clamp(2.5rem, 6vw, 4.5rem);
    font-weight: 750;
    letter-spacing: -0.055em;
    line-height: 1;
  }

  .lead {
    margin: 1.25rem auto 0;
    color: var(--muted-foreground);
    font-size: clamp(1rem, 2vw, 1.125rem);
    line-height: 1.7;
  }

  .site-footer {
    flex: 0 0 auto;
    padding: 1.5rem clamp(1.25rem, 4vw, 4rem) 2rem;
    text-align: center;
  }

  .copyright {
    margin: 0;
    color: var(--muted-foreground);
    font-size: 0.8125rem;
  }

  @media (max-width: 700px) {
    .site-header { min-height: 68px; }
  }
</style>
</head>
<body>
  <div class="page">
    <header class="site-header">
      <a class="wordmark" href="https://datpaq.com" aria-label="Datpaq home">DP.</a>
    </header>

    <main>
      <section class="success" aria-labelledby="success-title">
        <div class="success-icon" aria-hidden="true">✓</div>
        <h1 id="success-title">Signed in</h1>
        <p class="lead">Return to your terminal. You can safely close this window.</p>
      </section>
    </main>

    <footer class="site-footer">
      <p class="copyright">&copy; 2026 DATPAQ, Inc. All rights reserved.</p>
    </footer>
  </div>
</body>
</html>
`
